### PR TITLE
Update README.md with Table of Content

### PR DESCRIPTION
**Pull request by lucas-c9**
I added the table of content, I think you could change what you want.

### CODE REVIEW

**Review by ahammadshawki8 — CHANGES_REQUESTED** [review]
I wanted to create table_of_contents for the python scripts I have on this repo, not the README.md sections.

**Comment by lucas-c9** [comment]
Python scripts are the pythonN (python01, python02....) files?

**Review by ahammadshawki8 — CHANGES_REQUESTED** [review]
Great, but can you place the table of content between the description of the repo and the resources/materials. And also please use a bigger font for the `<summary>Table of Contents</summary>`.

**Review by ahammadshawki8 — APPROVED** [review]
Thanks, just as I wanted. Hoping to collaborate with you soon.

**Pull request merged**
